services:
  web:
    build: ./web
    network_mode: host
    environment:
      PORT: 3000

  gst-producer-ball:
    build: ./gst-producer
    network_mode: host
    environment:
      PATTERN: ball

  gst-producer-smpte:
    build: ./gst-producer
    network_mode: host
    environment:
      PATTERN: smpte

  gst-producer-spokes:
    build: ./gst-producer
    network_mode: host
    environment:
      PATTERN: spokes
